### ISSUE TITLE
hbase shell breaks if you try to delete input using backspace button

### ISSUE THREAD

**Issue by 10101010** [ipogudin/cloudera-cluster-docker#1]
Steps:
- Enter gateway's container bash session
- 'hbase shell'
- Enter some text "test"
- Delete last symbol using backspace button

Actual result:
``hbase(main):001:0> eConsoleReader.java:1414:in `backspace': java.lang.ArithmeticException: / by zero
	from ConsoleReader.java:1436:in `backspace'
	from ConsoleReader.java:628:in `readLine'
	from ConsoleReader.java:457:in `readLine'
	from Readline.java:237:in `s_readline'
	from Readline$s$s_readline.gen:65535:in `call'
	from CachingCallSite.java:332:in `cacheAndCall'
	from CachingCallSite.java:203:in `call'
	from FCallTwoArgNode.java:38:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from IfNode.java:111:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:147:in `call'
	from DefaultMethod.java:183:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from CallNoArgNode.java:63:in `interpret'
	from DAsgnNode.java:110:in `interpret'
	from IfNode.java:111:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:111:in `INTERPRET_BLOCK'
	from InterpretedBlock.java:374:in `evalBlockBody'
	from InterpretedBlock.java:295:in `yield'
	from InterpretedBlock.java:229:in `yieldSpecific'
	from Block.java:99:in `yieldSpecific'
	from ZYieldNode.java:25:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from EnsureNode.java:96:in `interpret'
	from BeginNode.java:83:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:212:in `call'
	from DefaultMethod.java:207:in `call'
	from CachingCallSite.java:322:in `cacheAndCall'
	from CachingCallSite.java:178:in `callBlock'
	from CachingCallSite.java:187:in `callIter'
	from FCallOneArgBlockNode.java:34:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from ASTInterpreter.java:111:in `INTERPRET_BLOCK'
	from InterpretedBlock.java:374:in `evalBlockBody'
	from InterpretedBlock.java:328:in `yield'
	from BlockBody.java:73:in `call'
	from Block.java:89:in `call'
	from RubyProc.java:270:in `call'
	from RubyProc.java:220:in `call'
	from RubyProc$i$0$0$call.gen:65535:in `call'
	from DynamicMethod.java:203:in `call'
	from DynamicMethod.java:199:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from CallNoArgNode.java:63:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:147:in `call'
	from DefaultMethod.java:183:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from VCallNode.java:86:in `interpret'
	from IfNode.java:111:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from WhileNode.java:131:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:147:in `call'
	from DefaultMethod.java:183:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from CallNoArgNode.java:63:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from IfNode.java:117:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:190:in `call'
	from DefaultMethod.java:199:in `call'
	from CachingCallSite.java:312:in `cacheAndCall'
	from CachingCallSite.java:169:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from ReturnNode.java:92:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from CaseNode.java:138:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:190:in `call'
	from DefaultMethod.java:199:in `call'
	from CachingCallSite.java:312:in `cacheAndCall'
	from CachingCallSite.java:169:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from RescueNode.java:216:in `executeBody'
	from RescueNode.java:120:in `interpretWithJavaExceptions'
	from RescueNode.java:110:in `interpret'
	from BeginNode.java:83:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from WhileNode.java:131:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:147:in `call'
	from DefaultMethod.java:183:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from VCallNode.java:86:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from CallOneArgNode.java:57:in `interpret'
	from OrNode.java:95:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from AndNode.java:91:in `interpret'
	from OrNode.java:95:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from UntilNode.java:116:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:147:in `call'
	from DefaultMethod.java:183:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from VCallNode.java:86:in `interpret'
	from DAsgnNode.java:110:in `interpret'
	from IfNode.java:111:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from RescueNode.java:216:in `executeBody'
	from RescueNode.java:120:in `interpretWithJavaExceptions'
	from RescueNode.java:110:in `interpret'
	from BeginNode.java:83:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from ASTInterpreter.java:111:in `INTERPRET_BLOCK'
	from InterpretedBlock.java:374:in `evalBlockBody'
	from InterpretedBlock.java:295:in `yield'
	from InterpretedBlock.java:229:in `yieldSpecific'
	from Block.java:99:in `yieldSpecific'
	from RubyKernel.java:1439:in `loop'
	from RubyKernel$s$0$0$loop.gen:65535:in `call'
	from CachingCallSite.java:302:in `cacheAndCall'
	from CachingCallSite.java:144:in `callBlock'
	from CachingCallSite.java:153:in `callIter'
	from FCallNoArgBlockNode.java:32:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from ASTInterpreter.java:111:in `INTERPRET_BLOCK'
	from InterpretedBlock.java:374:in `evalBlockBody'
	from InterpretedBlock.java:347:in `yield'
	from InterpretedBlock.java:304:in `yield'
	from Block.java:130:in `yield'
	from RubyContinuation.java:106:in `enter'
	from RubyKernel.java:1212:in `rbCatch'
	from RubyKernel$s$1$0$rbCatch.gen:65535:in `call'
	from CachingCallSite.java:322:in `cacheAndCall'
	from CachingCallSite.java:178:in `callBlock'
	from CachingCallSite.java:187:in `callIter'
	from FCallOneArgBlockNode.java:34:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:169:in `call'
	from DefaultMethod.java:191:in `call'
	from CachingCallSite.java:302:in `cacheAndCall'
	from CachingCallSite.java:144:in `callBlock'
	from CachingCallSite.java:153:in `callIter'
	from CallNoArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from ASTInterpreter.java:74:in `INTERPRET_METHOD'
	from InterpretedMethod.java:147:in `call'
	from DefaultMethod.java:183:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from /usr/lib/hbase/bin/../bin/hirb.rb:205:in `block_2$RUBY$start'
	from usr$lib$hbase$bin$$_dot_dot_$bin$hirb$block_2$RUBY$start:65535:in `call'
	from CompiledBlock.java:112:in `yield'
	from CompiledBlock.java:95:in `yield'
	from Block.java:130:in `yield'
	from RubyContinuation.java:106:in `enter'
	from RubyKernel.java:1212:in `rbCatch'
	from RubyKernel$s$1$0$rbCatch.gen:65535:in `call'
	from CachingCallSite.java:322:in `cacheAndCall'
	from CachingCallSite.java:178:in `callBlock'
	from CachingCallSite.java:187:in `callIter'
	from /usr/lib/hbase/bin/../bin/hirb.rb:204:in `method__5$RUBY$start'
	from usr$lib$hbase$bin$$_dot_dot_$bin$hirb$method__5$RUBY$start:65535:in `call'
	from DynamicMethod.java:203:in `call'
	from CompiledMethod.java:255:in `call'
	from CachingCallSite.java:292:in `cacheAndCall'
	from CachingCallSite.java:135:in `call'
	from /usr/lib/hbase/bin/../bin/hirb.rb:210:in `__file__'
	from /usr/lib/hbase/bin/../bin/hirb.rb:-1:in `load'
	from Ruby.java:697:in `runScript'
	from Ruby.java:690:in `runScript'
	from Ruby.java:597:in `runNormally'
	from Ruby.java:446:in `runFromMain'
	from Main.java:369:in `doRunFromMain'
	from Main.java:258:in `internalRun'
	from Main.java:224:in `run'
	from Main.java:208:in `run'
	from Main.java:188:in `main'``

**Comment by ipogudin** [comment]
Ruslan, this is not an issue with cloudera docker images. It's an issue with how docker sets the width and height of a terminal window when exec command is performed. It is easy to check with the following commands:
```
$ docker exec -it gateway stty size
0 0
$ docker exec -it gateway bash
# stty size
36 153
```
I suggest a couple of workarounds:
To run bash in docker exec and then run hbase shell
```
$ docker exec -it gateway bash
# hbase shell
```
or, to add the terminal size explicitly
```
docker exec -it gateway bash -c "stty rows 28 && stty cols 100 && hbase shell"
```
